### PR TITLE
learnMore.js/html

### PR DESCRIPTION
**Pull request by Ch4nd1erB1ng**

### CODE REVIEW

**Review by JonJonS06 — CHANGES_REQUESTED** [review]
Please add boilerplate to html. You can do this by typing html 5 on line one.

**Review by JonJonS06 — CHANGES_REQUESTED** [review]
Hate to be picky but can you remove the original script.js link on line 17?

**Comment by Ch4nd1erB1ng** [comment]
ok, I removed the original JS link

**Review by JonJonS06 — APPROVED** [review]
Looks good. Thank you

**Pull request merged**
